### ISSUE TITLE
Upgrade to Django 3.0 upon release

### ISSUE THREAD

**Issue by lpulley** [uiuc-mrdc/cogs#3]
So, Django 3.0 is planned to be released in December of this year: https://docs.djangoproject.com/en/dev/releases/3.0/

In the spirit of making this maintainable and not gross and deprecated, we should definitely upgrade to Django 3.0 as soon as it is officially released. Luckily for us, it appears [Djongo](https://github.com/nesdis/djongo) is actively developed and I would be surprised if it doesn't already support Django 3.0.

Upgrading should be as simple as changing the [Django Python requirements](https://github.com/uiuc-mrdc/cogs/blob/master/django/requirements.txt) from `>=2.0,<3.0` to `>=3.0,<4.0` and ensuring that we don't have anything in our code that will be changed:

- [Removed features in 3.0](https://docs.djangoproject.com/en/dev/releases/3.0/#removed-features-3-0)
- [Features deprecated but still included in 3.0](https://docs.djangoproject.com/en/dev/releases/3.0/#deprecated-features-3-0)
- [Breaking changes in 3.0](https://docs.djangoproject.com/en/dev/releases/3.0/#backwards-incompatible-3-0)

**Comment by lpulley** [comment]
@Timur2012 and anyone else helping with Django, I recommend you skim through the [Django 3.0 release notes](https://docs.djangoproject.com/en/dev/releases/3.0/) before submitting any pull requests to `master` for Django stuff, and make sure everything abides by the changes.

This way, when Django 3.0 is officially released, we can just hop over to the new version without any trouble. 👍

**Comment by lpulley** [comment]
Skimming through the release notes should also apply to pull request reviewers. If you're reviewing a pull request for Django stuff, definitely make sure any changes still abide by the Django 3.0 changes.

**Comment by lpulley** [comment]
[It's out!](https://www.djangoproject.com/weblog/2019/dec/02/django-3-released/)

Looks like ASGI should be nice for WebSockets but I don't understand it enough to see why exactly. I'll be looking into it.

**Comment by lpulley** [comment]
I believe someone mentioned Daphne: https://docs.djangoproject.com/en/3.0/howto/deployment/asgi/daphne/

**Comment by mgale456** [comment]
I got it working in the `playing_with_models` branch with MariaDb.

It only works on the second start of the container, since Django tries connecting before MariaDb is initialized.

So the way to get it running is currently:

```
docker-compose up
Ctrl-C  once mariaDB is done (should see it set up on port 3306)
docker-compose up -d
docker-compose exec python manage.py migrate
```

Whereas it ideally is:
```
docker-compose up -d
docker-compose exec python manage.py migrate
```

It also should be noted that `docker-compose down` is bad, since it stops and removes the containers. MariaDb recreates our database on startup, so it should never be removed and restarted. `docker-compose stop` works just fine with `docker-compose up -d`

Another note: I didn't change anything about ASGI. It is still just using Channels's implementation that worked in Django 2.0.

**Comment by mgale456** [comment]
Fixed the problem with it not initializing correctly since Django started too early. Now using `wait-for-it.sh` to delay starting the Django server

While hunting for that, "Thilak" in [this stackexchange post](https://stackoverflow.com/questions/54479941/how-to-init-mysql-database-in-docker-compose) has a potential solution to the db container overwriting the database on startup using `./docker-entrypoint-initdb.d` with some sql files to initialize.

Still need to update ASGI too, but almost ready to do a big merge request including Django 3.0 and everything else.

**Comment by lpulley** [comment]
The philosophy with Docker is that we should be able to remove and recreate the container without loss of data. The volume `mariadbdata` is supposed to hold onto the database for us. If it's not doing that I think we need to change the `- mariadbdata:/data/db` line.

EDIT: That line should say `- mariadbdata:/var/lib/mysql`. I'll update it in `django3`, see the comment below.

**Comment by lpulley** [comment]
Also @mgale456 I was working on the Django 3.0 and MariaDB changes in the `django3` branch. I don't think you should make those changes in `playing_with_models` at the same time. I'll make sure I've pushed my latest `django3`.

If you want Django 3.0 and MariaDB in `playing_with_models` you should finish the `django3` branch and merge it into `master`, then merge `master` into `playing_with_models`. I'm busy this week but I can get to it over break. For now I would strongly recommend reverting `playing_with_models` back to Django 2 and MongoDB, until `django3` is complete. Continuing this way means that `playing_with_models` isn't just about playing with models anymore, and so merging that branch into master later will be a huge change that's not just one feature.

**Comment by lpulley** [comment]
This work has been completed and merged to `master`.
