### ISSUE TITLE
Trying to migrate in the dockerfile

### ISSUE THREAD

**Issue by mgale456** [uiuc-mrdc/cogs#4]
I tried running `CMD python manage.py migrate` in the dockerfile. It didn't work. In testing it, it seems that the line `CMD python manage.py runserver 0.0.0.0:8000` doesn't run. Even when deleting it it changes nothing. Definitely needs more investigating, since the server does still start up. I may have just done something else wrong

**Comment by lpulley** [comment]
I'm a bit confused. Why does it seem that `python manage.py runserver 0.0.0.0:8000` doesn't run? I can explain, though, why nothing changed when you changed lines in the Dockerfile: you need to delete the existing image first (with `docker rmi cogs_web`) in order to force Compose to rebuild the image when it next brings up the `web` service.

Also, [only the last CMD in a Dockerfile takes effect](https://docs.docker.com/engine/reference/builder/#cmd) because `CMD` in a Dockerfile means "this is the default command to run when starting this container." Containers should only run one main process, and they should quit when the process exits. If you want to start the container with a different command, you can set `command:` in `docker-compose.yml` to choose a different command at runtime.

**However**, the main problem here is that the point of `migrate` is to create models in the database, which is a separate service. When building the image we cannot use the database yet, because we're building an image, not starting the Compose. You'll see if you add `RUN python manage.py migrate --noinput` before the `CMD` line in the Dockerfile that the build process hangs and then fails because it can't connect to `db`.

Apologies for the late reply! This prompted me to go get my GitHub notifications sorted out. I'll have a better eye on these moving forward. This is definitely the right place for these questions, so that they'll be well-documented.

I think for now we'll stick with manually running `docker-compose exec web python manage.py migrate` when starting with a fresh database. That should only happen once in a great while, or when developing, so I'm not too concerned about it. Basically, you only have to run it if `./data-db` didn't exist when starting the `db` service.

Thanks for getting into this @mgale456!

**Comment by mgale456** [comment]
That makes a lot more sense now why it wasn't working as expected. I had misinterpreted what `docker-compose down` does from the readme. I had thought it removed everything except volumes so I could rebuild it all with `up`. Now I know for testing the dockerfile I should use `docker-compose down --rmi all`

**Comment by lpulley** [comment]
Yeah, apologies for the confusion, I wasn't expecting anyone to play with the Dockerfile, but I'm glad you are. Nice to have another set of eyes.
